sitefoody/auth/urls.py
from django.urls import path, include

from foodapp.views import *

urlpatterns = [
    path('', include('djoser.urls')),
    path('auth_token/', include('djoser.urls.authtoken')),
]

sitefoody/foodapp/urls.py
from django.urls import path

from foodapp.views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('blogs/', BlogsPage.as_view(), name='blogs'),
    path('blogs/category/<slug:category_slug>/', CategoryBlogPage.as_view(), name='category_blog'),
    path('blogs/tag/<slug:tag_slug>/', TagBlogPage.as_view(), name='tag_blog'),
    path('blogs/<slug:detail_slug>/', DetailBlogPage.as_view(), name='detail_blog'),
    path('recipes/', RecipesPage.as_view(), name='recipes'),
    path('about/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
]

sitefoody/sitefoody/urls.py
from django.contrib import admin
from django.urls import path, include
from sitefoody import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foodapp.urls')),
    path('api/v1/auth/', include('auth.urls')),
    path('api/v1/', include('foodapp_api.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitefoody/foodapp/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver

User = get_user_model()


class Dish(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название блюда')
    slug = models.SlugField(max_length=150, unique=True, db_index=True, verbose_name='URL')
    recipe = models.TextField()
    description = models.TextField(blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to="image/%Y/%m/%d/")
    special_menu = models.BooleanField()
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'
        ordering = ['-time_create']


class Category(models.Model):
    """Категории блюд"""
    name = models.CharField(max_length=100, verbose_name='Категория')
    slug = models.SlugField(max_length=100, unique=True, db_index=True)
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Тэг')
    slug = models.SlugField(max_length=100, unique=True, db_index=True)

    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     if self.name[0] != '#':
    #         self.name = '#' + self.name
    #     super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag_blog', kwargs={'tag_slug': self.slug})

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'
        ordering = ['id']


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=150)
    time_create = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-time_create']


class Blog(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название блога')
    slug = models.SlugField(max_length=150, unique=True, db_index=True, verbose_name='URL')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="image/%Y/%m/%d/")
    content = models.TextField(blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField('CategoryBlog')
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail_blog', kwargs={'detail_slug': self.slug})

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ['-time_create']


class Cook(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя повара')
    position = models.CharField(max_length=100, verbose_name='Должность')
    photo = models.ImageField(upload_to="photo/%Y/%m/%d/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Повар'
        verbose_name_plural = 'Повары'
        ordering = ['id']


class Review(models.Model):
    content = models.TextField(blank=True)
    cook = models.ForeignKey(Cook, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'
        ordering = ['id']


class CategoryBlog(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_blog', kwargs={'category_slug': self.slug})

    class Meta:
        verbose_name = 'Категория блога'
        verbose_name_plural = 'Категории блогов'
        ordering = ['id']


class EmailForDistribution(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'email'
        verbose_name_plural = 'emails'
        ordering = ['id']

sitefoody/foodapp/forms.py
from django import forms
from .models import *
from phonenumber_field.formfields import PhoneNumberField


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ContactForm(forms.Form):
    name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = PhoneNumberField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', "rows": 5}))


class EmailForDistributionForm(forms.ModelForm):
    class Meta:
        model = EmailForDistribution
        fields = ['email']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter Email Address"}),
        }

sitefoody/foodapp/views.py
import json

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import FormMixin, FormView
from django.views.generic import ListView, DetailView
from .models import *
from .forms import *
from django.core.mail import send_mail
from .utils import *
from decouple import config
from .tasks import first_message_distribution


class HomePage(View):
    def get_context_data(self, *, object_list=None, **kwargs):
        special_menu = Dish.objects.filter(special_menu=True)[:5]
        dishs = Dish.objects.filter(special_menu=False)[:8]
        reviews = Review.objects.all().select_related('cook')
        blogs = Blog.objects.all()[:2]
        categories = Category.objects.all()[:4]
        email_distr_form = EmailForDistributionForm()
        context = {
            'special_menu': special_menu,
            'dishs': dishs,
            'reviews': reviews,
            'blogs': blogs,
            'categories': categories,
            'email_distr_form': email_distr_form,
        }
        return context

    def get(self, request):
        context = self.get_context_data()
        return render(request, 'foodapp/index.html', context=context)

    def post(self, request):
        email_distr_form = EmailForDistributionForm(request.POST)
        context = self.get_context_data() | {'email_distr_form': email_distr_form}

        if email_distr_form.is_valid():
            email_distr_form.save()
            first_message_distribution.delay(email_distr_form.instance.email)
            return redirect('home')

        return render(request, 'foodapp/index.html', context=context)


class BlogsPage(ListView):
    model = Blog
    template_name = 'foodapp/blogs.html'
    context_object_name = 'blogs'
    paginate_by = 4


class CategoryBlogPage(ListView):
    model = Blog
    template_name = 'foodapp/category_blogs.html'
    context_object_name = 'blogs'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Blog.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        category_model = CategoryBlog.objects.get(slug=self.kwargs['category_slug'])
        category = category_model.name
        return context | {'category': category}


class TagBlogPage(ListView):
    model = Blog
    template_name = 'foodapp/tag_blogs.html'
    context_object_name = 'blogs'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Blog.objects.filter(tag__slug=self.kwargs['tag_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_slug = self.kwargs['tag_slug']
        return context | {'tag_slug': tag_slug}


class DetailBlogPage(FormMixin, DetailView):
    model = Blog
    slug_url_kwarg = 'detail_slug'
    template_name = 'foodapp/detail_blog.html'
    context_object_name = 'blog'
    form_class = CreateCommentForm

    def get_queryset(self):
        return Blog.objects.filter(slug=self.kwargs['detail_slug']).select_related('author__profile')

    def get_success_url(self):
        return reverse('detail_blog', kwargs={'detail_slug': self.get_object().slug})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_blogs'] = CategoryBlog.objects.all()[:5]
        context['comments'] = Comment.objects.filter(blog__slug=self.kwargs['detail_slug']).defer(
            "blog").select_related('author__profile')
        context['form'] = CreateCommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.blog = self.get_object()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class RecipesPage(ListView):
    model = Dish
    template_name = 'foodapp/recipes.html'
    context_object_name = 'dishs'


class AboutPage(ListView):
    model = Cook
    template_name = 'foodapp/about.html'
    context_object_name = 'cooks'


class ContactPage(FormView):
    form_class = ContactForm
    template_name = 'foodapp/contact.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        name_country = country_definition(form.cleaned_data['phone'].country_code)
        message = form.cleaned_data['message'] + \
                  f"\n\nДанные отправителя:" \
                  f"\nТелефон: {form.cleaned_data['phone']}, Страна: {name_country}" \
                  f"\nEmail: {form.cleaned_data['email']}"
        send_mail('Contact',
                  message,
                  config('EMAIL_HOST_USER'),
                  [config('EMAIL_RECEIVES_MESSAGES')],
                  fail_silently=False)
        return super(ContactPage, self).form_valid(form)

sitefoody/foodapp/templates/foodapp/about.html
{% extends 'foodapp/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
{{ title }}{{ block.super }}
{% endblock %}

{% block content %}
{% include 'foodapp/inc/_slider.html' %}

<section class="section pt-5 top-slant-white2 relative-higher">
    <div class="container">
        <div class="row mb-5 justify-content-center" data-aos="fade">
            <div class="col-md-7 text-center heading-wrap">
                <h2 data-aos="fade-up">The Restaurant</h2>
                <p data-aos="fade-up" data-aos-delay="100">Far far away, behind the word mountains, far from the
                    countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                    right at the coast of the Semantics, a large language ocean.</p>
            </div>
        </div>
        <div class="row align-items-center mb-5">
            <div class="col-lg-4">
                <img src="{% static 'foodapp/img/dishes_1.jpg' %}" alt="Free website template by Free-Template.co"
                     class="img-fluid about_img_1" data-aos="fade" data-aos-delay="200">
            </div>
            <div class="col-lg-4">
                <img src="{% static 'foodapp/img/about_1.jpg' %}" alt="Free website template by Free-Template.co"
                     class="img-fluid about_img_1" data-aos="fade" data-aos-delay="300">
                <img src="{% static 'foodapp/img/about_2.jpg' %}" alt="Free website template by Free-Template.co"
                     class="img-fluid about_img_1" data-aos="fade" data-aos-delay="400">
            </div>
            <div class="col-lg-4">
                <img src="{% static 'foodapp/img/dishes_3.jpg' %}" alt="Free website template by Free-Template.co"
                     class="img-fluid about_img_1" data-aos="fade" data-aos-delay="500">
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 ml-auto">
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live
                    the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large
                    language ocean.</p>

                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a
                    paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
            <div class="col-md-6 ml-auto">
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live
                    the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large
                    language ocean.</p>

                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a
                    paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
        </div>
    </div>
</section>

<section class="section bg-light top-slant-white">

    <div class="clearfix mb-5 pb-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center heading-wrap">
                    <h2>Chefs</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="major-caousel js-carousel-1 owl-carousel">
                {% for cook in cooks %}
                <div>
                    <div class="media d-block media-custom text-center">
                        <a href="adoption-single.html"><img src="{{ cook.photo.url }}" alt="Image Placeholder"
                                                            class="img-fluid"></a>
                        <div class="media-body">
                            <h3 class="mt-0 text-black">{{ cook.name }}</h3>
                            <p class="lead">{{ cook.position }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- END slider -->
        </div>
    </div>

</section> <!-- .section -->

{% endblock %}

sitefoody/foodapp/templates/foodapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Foody &mdash; Website{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'foodapp/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'foodapp/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'foodapp/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodapp/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'foodapp/css/magnific-popup.css' %}">


    <link rel="stylesheet" href="{% static 'foodapp/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodapp/fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodapp/fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'foodapp/css/style.css' %}">
</head>
<body>

<!-- header -->
{% include 'foodapp/inc/_header.html' %}


{% block content %}{% endblock %}

<!-- paginator -->
{% if page_obj.has_other_pages %}
<div class="row mt-5" data-aos="fade-up">
    <div class="col-12 text-center">
        <nav aria-label="...">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
                {% endif %}

                {% for p in page_obj.paginator.page_range %}

                {% if page_obj.number == p %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ p }}">{{ p }} <span class="sr-only">(current)</span></a>
                </li>
                {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}

            </ul>
        </nav>
    </div>
</div>

{% endif %}

<!-- footer -->
{% include 'foodapp/inc/_footer.html' %}

<!-- loader -->
<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#cf1d16"/>
    </svg>
</div>

<script src="{% static 'foodapp/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'foodapp/js/popper.min.js' %}"></script>
<script src="{% static 'foodapp/js/bootstrap.min.js' %}"></script>
<script src="{% static 'foodapp/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'foodapp/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'foodapp/js/aos.js' %}"></script>

<script src="{% static 'foodapp/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'foodapp/js/magnific-popup-options.js' %}"></script>


<script src="{% static 'foodapp/js/main.js' %}"></script>

</body>
</html>

sitefoody/foodapp/templates/foodapp/blogs.html
{% extends 'foodapp/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
{{ title }}{{ block.super }}
{% endblock %}

{% include 'foodapp/inc/_slider.html' %}

{% block content %}
<section class="section bg-light pt-0 bottom-slant-gray">
    <div class="container">
        <div class="row">
            {% for blog in blogs %}
            <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="blog d-block">
                    <a class="bg-image d-block" href="{{ blog.image.url }}"
                       style="background-image: url({{ blog.image.url }});"></a>
                    <div class="text">
                        <h3><a href="single.html">{{ blog.name }}</a></h3>
                        <p class="sched-time">
                            <span><span class="fa fa-calendar"></span> {{ blog.time_create }}</span> <br>
                        </p>
                        <p>{{ blog.content|truncatewords:20 }}</p>

                        <p><a href="#" class="btn btn-primary btn-sm">Read More</a></p>

                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

    

sitefoody/foodapp/templates/foodapp/category_blogs.html
{% extends 'foodapp/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
{{ title }}{{ block.super }}
{% endblock %}



{% block content %}

{% include 'foodapp/inc/_slider.html' %}


<section class="section bg-light pt-0 bottom-slant-gray">
    <h1>Выбрана категория - {{ category_slug }}</h1>

    <div class="container">
        <div class="row">
            {% for blog in blogs %}
            <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="blog d-block">
                    <a class="bg-image d-block" href="{{ blog.image.url }}"
                       style="background-image: url({{ blog.image.url }});"></a>
                    <div class="text">
                        <h3><a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a></h3>
                        <p class="sched-time">
                            <span><span class="fa fa-calendar"></span> {{ blog.time_create }}</span> <br>
                        </p>
                        <p>{{ blog.content|truncatewords:20 }}</p>

                        <p><a href="{{ blog.get_absolute_url }}" class="btn btn-primary btn-sm">Read More</a></p>

                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

    

sitefoody/foodapp/templates/foodapp/detail_blog.html
{% extends 'foodapp/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
{{ title }}{{ block.super }}
{% endblock %}


{% block content %}


<div class="slider-wrap">
    <div class="slider-item" style="background-image: url({{ blog.image.url }});">

        <div class="container">
            <div class="row slider-text align-items-center justify-content-center">
                <div class="col-md-8 text-center col-sm-12 ">
                    <p class="mb-2" data-aos="fade-up">{{ blog.time_create }} <span class="mx-3">&bullet;</span> Posted
                        by <a
                                href="#" target="_blank">{{ blog.author }}</a></p>
                    <h1 data-aos="fade-up" data-aos-delay="100">{{ blog.name }}</h1>

                </div>
            </div>
        </div>

    </div>
    <!-- END slider -->
</div>


<section class="section pt-4 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 blog-content">
                <h3 class="mb-4">{{ blog.name }}</h3>
                <p>{{ blog.content }}</p>
                <p><img src="{{blog.image.url}}" alt="Image" class="img-fluid rounded"></p>


                <div class="pt-5">

                    <p>Categories:
                        {% for category in blog.category.all %}
                        {% if forloop.last %}
                        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                        {% else %}
                        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>,
                        {% endif %}
                        {% endfor %}
                        Tags:
                        {% for tag in blog.tag.all %}
                        {% if forloop.last %}
                        <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                        {% else %}
                        <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>,
                        {% endif %}
                        {% endfor %}

                </div>

                <!-- comment-list -->
                <div class="pt-5">
                    {% if blog.comment_set.all|length == 0 %}
                    <h3 class="mb-5">Комментариев нет</h3>
                    {% else %}
                    <h3 class="mb-5">Количество комментариев: {{ comments|length }}</h3>
                    {% endif %}
                    <ul class="comment-list">
                        {% for comment in comments %}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{{ comment.author.profile.photo.url }}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.author }}</h3>
                                <div class="meta">{{ comment.time_create }}</div>
                                <p>{{ comment.content }}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                        {% endfor %}
                        <!-- END comment-list -->


                        {% if request.user.is_authenticated %}
                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form action="" method="post">
                                {% csrf_token %}

                                <div class="form-group">
                                    <label>{{ form.content.label }}</label>
                                    {{ form.content }}
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn btn-primary btn-md">
                                </div>

                            </form>
                        </div>
                        {% else %}
                        <h1>Авторизуйтесь чтоб оставлять комментарии</h1>
                        {% endif %}


                </div>

            </div>

            <div class="col-lg-4 sidebar pl-lg-5">
                <div class="sidebar-box">
                    <img src="{{blog.author.profile.photo.url}}" alt="Image placeholder"
                         class="img-fluid mb-4 w-50 rounded-circle">
                    <h3><a href="#">{{ blog.author }}</a></h3>
                    <p>{{ blog.author.profile.about_me|truncatewords:10 }}</p>

                </div>

                <div class="sidebar-box">
                    <div class="categories">
                        <h3>Categories Blog</h3>
                        {% for category_blog in category_blogs %}
                        <li><a href="{{ category_blog.get_absolute_url }}">{{ category_blog.name }}<span>({{ category_blog.blog_set.all|length }})</span></a>
                        </li>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

sitefoody/foodapp/templates/foodapp/recipes.html
{% extends 'foodapp/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
{{ title }}{{ block.super }}
{% endblock %}

{% block content %}
{% include 'foodapp/inc/_slider.html' %}


<section class="section bg-light pt-0 bottom-slant-gray">

    <div class="clearfix mb-5 pb-5">
        <div class="container-fluid">
            <div class="row" data-aos="fade">
                <div class="col-md-12 text-center heading-wrap">
                    <h2>Our Recipes</h2>
                    <h3>Number of recipes: {{ dishs|length }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="row no-gutters">

            {% for dish in dishs %}
            {% if forloop.counter0|divisibleby:"2" %}
            <div class="col-md-6">
                <div class="sched d-block d-lg-flex">
                    <div class="bg-image order-2" style="background-image: url({{ dish.image.url }});"
                         data-aos="fade"></div>
                    <div class="text order-1">
                        <h3>{{ dish.name }}</h3>
                        <p>{{ dish.description|truncatewords:15 }}</p>
                        <p class="text-primary h3">${{ dish.price }}</p>
                    </div>
                </div>
                {% else %}
                <div class="sched d-block d-lg-flex">
                    <div class="bg-image" style="background-image: url({{ dish.image.url }});" data-aos="fade"></div>
                    <div class="text">
                        <h3>{{ dish.name }}</h3>
                        <p>{{ dish.description|truncatewords:15 }}</p>
                        <p class="text-primary h3">${{ dish.price }}</p>

                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section> <!-- .section -->


{% endblock %}

sitefoody/foodapp/templates/foodapp/tag_blogs.html
{% extends 'foodapp/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
{{ title }}{{ block.super }}
{% endblock %}



{% block content %}

{% include 'foodapp/inc/_slider.html' %}


<section class="section bg-light pt-0 bottom-slant-gray">
    <h1>Выбран тэг - #{{ tag_slug }}</h1>

    <div class="container">
        <div class="row">
            {% for blog in blogs %}
            <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="blog d-block">
                    <a class="bg-image d-block" href="{{ blog.image.url }}"
                       style="background-image: url({{ blog.image.url }});"></a>
                    <div class="text">
                        <h3><a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a></h3>
                        <p class="sched-time">
                            <span><span class="fa fa-calendar"></span> {{ blog.time_create }}</span> <br>
                        </p>
                        <p>{{ blog.content|truncatewords:20 }}</p>

                        <p><a href="{{ blog.get_absolute_url }}" class="btn btn-primary btn-sm">Read More</a></p>

                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

    